server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # API 요청 → 게이트웨이 프록시
    location ~* ^/(auth|products|orders|users|payments)/ {
        proxy_pass http://lp-gateway:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # React Router SPA 라우팅
    location / {
        try_files $uri $uri/ /index.html;
    }
}
